version: "2.4"
services:
  nginx:
    image: nginx
    volumes:
      - "./nginx/dev.conf:/etc/nginx/conf.d/default.conf"
      - './nginx/.htpasswd:/etc/nginx/.htpasswd'
      - './nginx/dhparam.pem:/etc/nginx/ssl/dhparam.pem'
      - './nginx/zen.crt:/etc/nginx/ssl/zen.crt'
      - './nginx/entrust-zen.pole-emploi.fr-key.pem:/etc/nginx/ssl/entrust-zen.pole-emploi.fr-key.pem'
      - './api/extracts:/home/extracts'
      - './front:/home/front'
      - './front-admin:/home/front-admin'
      - './nginx/var/log/nginx:/var/log/nginx'

  api:
    volumes:
      - './api:/home/api'

  front:
    container_name: 'zen-createur-front_${ZEN_ENV}'
    image: node:12.16.1
    restart: unless-stopped
    volumes:
      - './front:/home/front'
    expose:
      - '3000'
    env_file:
      - .env.${ZEN_ENV}
    command: > 
      bash -c "cd /home/front &&
        (which yarn || npm i -g yarn@1.15.2) &&
        yarn install && 
        yarn start;"
    environment:
      - TZ=Europe/Paris
    networks:
      zc_network:
        ipv4_address: 172.0.0.110

  front-admin:
    container_name: 'zen-createur-frontadmin_${ZEN_ENV}'
    image: node:12.16.1
    restart: unless-stopped
    volumes:
      - './front-admin:/home/front'
    expose:
      - '3000'
    env_file:
      - .env.${ZEN_ENV}
    command: > 
      bash -c "cd /home/front &&
        (which yarn || npm i -g yarn@1.15.2) &&
        yarn install && 
        yarn start;"
    environment:
      - TZ=Europe/Paris
    networks:
      zc_network:
        ipv4_address: 172.0.0.111

  db:
    ports:
      - "5432:5432"
