version: '2.4'
services:
  nginx:
    build:
      context: .
      dockerfile: ./dockerfile_nginx_prod
      args:
        ZEN_ENV: ${ZEN_ENV}
    volumes:
      - './var/log/nginx:/var/log/nginx'

  api:
    volumes:
      - './var/log/zen-createur_api:/var/log/zen-createur_api'
    environment:
      - WINSTON_FILE_FOLDER=/var/log/zen-createur_api