version: '2.4'
services:
  nginx:
    image: zen-createur-nginx_${ZEN_ENV}:${BUILD_VERSION}
    build:
      context: .
      dockerfile: ./dockerfile_nginx_prod
      args:
        ZEN_ENV: ${ZEN_ENV}
    volumes:
      - './var/log/nginx:/var/log/nginx'

  api:
    image: zen-createur-api_${ZEN_ENV}:${BUILD_VERSION}
    volumes:
      - './var/log/zen-createur_api:/var/log/zen-createur_api'
    environment:
      - WINSTON_FILE_FOLDER=/var/log/zen-createur_api
