# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01

    working_directory: ~/zen-createur

    steps:
      - run:
          name: Upgrade max watchable files to avoid ENOSPC
          command: sudo sysctl -w fs.inotify.max_user_watches=524288

      - run:
          name: Install node@10.15 (need right version for `yarn`)
          command: |
            set +e
            curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash
            export NVM_DIR="/opt/circleci/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install v10.15

            # Each step uses the same `$BASH_ENV`, so need to modify it
            # roundabout way of specifying we want to use node 10 on every command.
            echo 'export NVM_DIR="/opt/circleci/.nvm"' >> $BASH_ENV
            echo "[ -s \"$NVM_DIR/nvm.sh\" ] && . \"$NVM_DIR/nvm.sh\"" >> $BASH_ENV
            echo "nvm use v10.15" >> $BASH_ENV

      - run: npm i -g yarn

      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn

      - run:
          name: Build front for Bundle analyzer
          command: cd front; yarn && CI=false yarn build; cd ../

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      # run tests!
      - run: yarn test:all

      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
